### ISSUE TITLE
Support for cross-browser web extensions

### ISSUE THREAD

**Issue by kalikiana** [midori-browser/core#244]
Aside from its own native extension (plugin) interface Midori should support cross-browser extension APIs. The use cases are:

- Use existing extensions for other browsers
- Facilitate feature development based on web technologies
- Share extensions between platforms (Android, GTK+)

Proposal:
- [x] Recognize `manifest.json` analogous to `*.plugin` #250
- [x] Content scripts/ styles #250
- [x] Background page/ scripts #250
- [ ] API exposed to content scripts
- [x] Browser action in toolbar #250
- [ ] Page action in urlbar
- [ ] Sidebar support
- [ ] Context menu
- [ ] Proxy override
- [ ] Interception of network requests
- [ ] Hide buttons easily via right-click
- [ ] Keyboard shortcuts (commands)
- [ ] Manage web extensions in the preferences dialog
- [ ] Localization
- [ ] Options accessible from the preferences dialog
- [ ] Permissions
- [x] Load extensions from local folders #250
- [ ] Install extensions from the web
- [ ] Side-load extensions locally
- [ ] Unit tests
- [ ] Theme extensions

For reference:

- [Browser Extensions Spec](https://browserext.github.io/browserext/)
- [Web Extensions (MSDN)](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions)
- [Compatibility with Chrome in Microsoft Edge](https://docs.microsoft.com/en-us/microsoft-edge/extensions/api-support/supported-apis)
- [Chrome extensions](https://developer.chrome.com/extensions)

**Comment by kalikiana** [comment]
With initial (built-in) extension having landed, we can look into more specific aspects and interfaces to support as well as UX tasks as outlined in the proposal.

**Comment by zonia3000** [comment]
Hi, sorry for the stupid question... I'm developing a simple cross-browser extension, in which folder should I put it for trying it on Midori? I installed Midori on Ubuntu using snap.

**Comment by kalikiana** [comment]
> Hi, sorry for the stupid question... I'm developing a simple cross-browser extension, in which folder should I put it for trying it on Midori? I installed Midori on Ubuntu using snap.

It should go in `~/.local/share/midori/extensions/`, in the case of the snap you'll want to prefix it with the snap home i.e. `~/snap/midori/current/` so it would become `~/snap/midori/current/.local/share/midori/extensions/`.

**Comment by RJVB** [comment]
What else do you need to do to get an extension (say in a .xpi container) to load, or else to get some diagnostic output explaining why it isn't being loaded?

**Comment by alex-eri** [comment]
Using v9.0-7-gd8546ca from snap and dont see content_scripts loaded in inspector.
